"""Know what you hold, not just what it was worth

Four tables so a brokerage account is a list of positions rather than a single
number typed in by hand once a month.

`holdings` is a snapshot in the same shape as `account_balances` — one row per
position per date — and everything in it is a fact off the statement. No live
quote is ever written here. Marked-to-market values are derived on read, so an
afternoon of bad prices cannot become permanent history, and net worth stays a
record of things that were actually measured.

`securities.quote_symbol` carries the only genuinely hard case. Fidelity
reports the Moody's PPP position as CUSIP 31564E540, a collective investment
trust sold only inside employer plans: no ticker, and no provider will ever
quote it. At $123,959 that is 76% of the portfolio, so leaving it frozen
between statements would make "current" wrong on every day the market moved.
A proxy fixes it — the public twin FFIJX — but only its *movement* may be
borrowed. The trust trades at $22.70 a unit against FFIJX's $19.93, so
quantity x proxy price would understate the account by 14% on day one.

`security_prices` is not foreign-keyed to `securities` on purpose: FFIJX has
rows there and is held by nobody, and a constraint would force a fake holding
into existence to keep them.

Revision ID: 6e214d7ea0c2
Revises: 9a043eaea8ee
Create Date: 2026-08-08 12:22:51.127437

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e214d7ea0c2'
down_revision: str | Sequence[str] | None = '9a043eaea8ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('EQUITY', 'ETF', 'MUTUAL_FUND', 'MONEY_MARKET', 'UNQUOTED', name='security_kind'), nullable=False),
    sa.Column('quote_symbol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_securities'))
    )
    op.create_table('security_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_prices')),
    sa.UniqueConstraint('symbol', 'as_of', name=op.f('uq_security_prices_symbol'))
    )
    op.create_index(op.f('ix_security_prices_symbol'), 'security_prices', ['symbol'], unique=False)
    op.create_table('brokerage_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=60), nullable=False),
    sa.Column('external_number', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('external_name', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_brokerage_accounts_account_id_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brokerage_accounts')),
    sa.UniqueConstraint('account_id', name=op.f('uq_brokerage_accounts_account_id')),
    sa.UniqueConstraint('institution', 'external_number', name=op.f('uq_brokerage_accounts_institution'))
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_holdings_account_id_accounts')),
    sa.ForeignKeyConstraint(['symbol'], ['securities.symbol'], name=op.f('fk_holdings_symbol_securities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings')),
    sa.UniqueConstraint('account_id', 'as_of', 'symbol', name=op.f('uq_holdings_account_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    op.drop_table('brokerage_accounts')
    op.drop_index(op.f('ix_security_prices_symbol'), table_name='security_prices')
    op.drop_table('security_prices')
    op.drop_table('securities')
    # ### end Alembic commands ###
    # Dropping the table leaves the type behind, and the next upgrade then
    # fails on a name that already exists. Autogenerate never writes this.
    sa.Enum(name="security_kind").drop(op.get_bind(), checkfirst=True)
