"""fixed costs can have components

Revision ID: 212a433f617e
Revises: 3f67c2383208
Create Date: 2026-08-07 01:03:58.915479

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '212a433f617e'
down_revision: str | Sequence[str] | None = '3f67c2383208'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_costs', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_fixed_costs_parent_id_fixed_costs'), 'fixed_costs', 'fixed_costs', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_fixed_costs_parent_id_fixed_costs'), 'fixed_costs', type_='foreignkey')
    op.drop_column('fixed_costs', 'parent_id')
    # ### end Alembic commands ###
