"""accounts can be closed

Revision ID: 3f67c2383208
Revises: a07b40fcd91a
Create Date: 2026-08-07 00:57:56.607788

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3f67c2383208'
down_revision: str | Sequence[str] | None = 'a07b40fcd91a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('closed_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'closed_on')
    # ### end Alembic commands ###
