"""record merchant pairs that are not the same place

Revision ID: a07b40fcd91a
Revises: 40be6bb2bbb6
Create Date: 2026-08-06 23:40:46.499719

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a07b40fcd91a"
down_revision: str | Sequence[str] | None = "40be6bb2bbb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_splits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("left_name", sa.String(length=120), nullable=False),
        sa.Column("right_name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_splits")),
        sa.UniqueConstraint(
            "left_name", "right_name", name=op.f("uq_merchant_splits_left_name")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("merchant_splits")
    # ### end Alembic commands ###
