"""Sign in with Touch ID instead of typing a code

Revision ID: a036a91de122
Revises: 54fe608f2c3e
Create Date: 2026-08-08 01:29:05.292304

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a036a91de122'
down_revision: str | Sequence[str] | None = '54fe608f2c3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=500), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('transports', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], name=op.f('fk_passkeys_user_id_app_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passkeys')),
    sa.UniqueConstraint('credential_id', name=op.f('uq_passkeys_credential_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passkeys')
    # ### end Alembic commands ###
