"""merchants have a category history not a default

A merchant does not have a category, it has a history of them. Rhino Market &
Deli is Food and Drinks 74 times and Groceries 39, and both are right.

default_category_id recorded whichever transaction created the merchant and
never moved afterwards — not when the population changed, not when a merge
folded another merchant in. It contradicted the merchant's own history for
twelve of them, worst across 113 transactions, and nothing read it any more:
the import preview computes its suggestion from the transactions.

Dropping it removes the last stored copy of something already derivable, which
is the only kind of redundancy that can disagree with itself.

The downgrade restores the column but not the values. They were wrong.

Revision ID: 27022c3157a8
Revises: b7e1bf38495f
Create Date: 2026-08-07 09:44:56.829777

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27022c3157a8"
down_revision: str | Sequence[str] | None = "b7e1bf38495f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_merchants_default_category_id_categories"),
        "merchants",
        type_="foreignkey",
    )
    op.drop_column("merchants", "default_category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "merchants",
        sa.Column(
            "default_category_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("fk_merchants_default_category_id_categories"),
        "merchants",
        "categories",
        ["default_category_id"],
        ["id"],
    )
    # ### end Alembic commands ###
