"""fixed costs can name their merchant

Revision ID: 5bfe49e20056
Revises: 212a433f617e
Create Date: 2026-08-07 01:06:32.857593

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5bfe49e20056'
down_revision: str | Sequence[str] | None = '212a433f617e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_costs', sa.Column('merchant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_fixed_costs_merchant_id_merchants'), 'fixed_costs', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_fixed_costs_merchant_id_merchants'), 'fixed_costs', type_='foreignkey')
    op.drop_column('fixed_costs', 'merchant_id')
    # ### end Alembic commands ###
