"""initial schema

Revision ID: 5d308f00a86a
Revises:
Create Date: 2026-08-06 22:24:35.081181

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d308f00a86a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("is_retirement", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint(
            "institution", "name", name=op.f("uq_accounts_institution")
        ),
    )
    op.create_table(
        "budget_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "month between 1 and 12", name=op.f("ck_budget_periods_month_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_periods")),
        sa.UniqueConstraint("year", "month", name=op.f("uq_budget_periods_year")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("COMMITTED", "FLEXIBLE", "SAVINGS", "OTHER", name="category_kind"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "paycheck_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=80), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("INCOME", "INSURANCE", "SAVINGS", "TAX", name="paycheck_line_kind"),
            nullable=False,
        ),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paycheck_lines")),
    )
    op.create_table(
        "account_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_balances_account_id_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_balances")),
        sa.UniqueConstraint(
            "account_id", "as_of", name=op.f("uq_account_balances_account_id")
        ),
    )
    op.create_table(
        "budget_allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_budget_allocations_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["budget_periods.id"],
            name=op.f("fk_budget_allocations_period_id_budget_periods"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_allocations")),
        sa.UniqueConstraint(
            "period_id", "category_id", name=op.f("uq_budget_allocations_period_id")
        ),
    )
    op.create_table(
        "fixed_costs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=80), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("is_exact", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_fixed_costs_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixed_costs")),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=120), nullable=False),
        sa.Column("default_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["default_category_id"],
            ["categories.id"],
            name=op.f("fk_merchants_default_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
        sa.UniqueConstraint("canonical_name", name=op.f("uq_merchants_canonical_name")),
    )
    op.create_table(
        "merchant_patterns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_merchant_patterns_merchant_id_merchants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_patterns")),
        sa.UniqueConstraint("pattern", name=op.f("uq_merchant_patterns_pattern")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=True),
        sa.Column("period_id", sa.Integer(), nullable=False),
        sa.Column("raw_description", sa.String(length=200), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("WORKBOOK", "CSV", "MANUAL", name="transaction_source"),
            nullable=False,
        ),
        sa.Column("import_hash", sa.String(length=64), nullable=True),
        sa.Column("source_ref", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_transactions_merchant_id_merchants"),
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["budget_periods.id"],
            name=op.f("fk_transactions_period_id_budget_periods"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("import_hash", name=op.f("uq_transactions_import_hash")),
    )
    op.create_index(
        "ix_transactions_occurred_on", "transactions", ["occurred_on"], unique=False
    )
    op.create_index(
        "ix_transactions_period_category",
        "transactions",
        ["period_id", "category_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_period_category", table_name="transactions")
    op.drop_index("ix_transactions_occurred_on", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("merchant_patterns")
    op.drop_table("merchants")
    op.drop_table("fixed_costs")
    op.drop_table("budget_allocations")
    op.drop_table("account_balances")
    op.drop_table("paycheck_lines")
    op.drop_table("categories")
    op.drop_table("budget_periods")
    op.drop_table("accounts")
    # ### end Alembic commands ###
